# Generated by Django 3.2.4 on 2021-10-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
