# Generated by Django 3.2.4 on 2021-07-01 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tags", "0001_initial"),
        ("comments", "0003_initial"),
        ("topics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="creator",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="issue",
            name="description",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="comments.startingcomment"),
        ),
        migrations.AddField(
            model_name="issue",
            name="tags",
            field=models.ManyToManyField(blank=True, to="tags.Tag"),
        ),
        migrations.AddField(
            model_name="issue",
            name="topic",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="topics.topic"),
        ),
    ]
