# Generated by Django 3.2.4 on 2021-07-13 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("progress_report", "0003_remove_progressreport_topic"),
        ("topics", "0003_auto_20210706_1255"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="progress_report",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topic",
                to="progress_report.progressreport",
            ),
        ),
    ]
