# Generated by Django 3.2.4 on 2021-07-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0004_topic_progress_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
