# Generated by Django 3.2.4 on 2021-07-18 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0007_auto_20210717_1646"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issue",
            options={"ordering": ("-date",)},
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ("-updated_on", "-stars")},
        ),
    ]
