# Generated by Django 3.2.4 on 2021-07-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0008_auto_20210718_1720"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="no_of_comments",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
