# Generated by Django 3.2.4 on 2021-07-21 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0004_auto_20210716_1311"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="members",
            field=models.ManyToManyField(blank=True, related_name="member_of_orgs", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="organization",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="orgs", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
