# Generated by Django 3.2.4 on 2021-07-22 05:04

from django.db import migrations, models
import the_water_project.users.models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0005_auto_20210721_1759"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to=the_water_project.users.models.unique_file_path),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to=the_water_project.users.models.unique_file_path),
        ),
    ]
