# Generated by Django 3.2.4 on 2021-07-06 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("topics", "0003_auto_20210706_1255"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgressReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total_no_of_tasks", models.PositiveIntegerField(default=0)),
                ("no_of_tasks_completed", models.PositiveIntegerField(default=0)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("topic", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="topics.topic")),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "progress_report",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="progress_report.progressreport"),
                ),
            ],
        ),
    ]
