# Generated by Django 3.2.4 on 2021-07-13 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("progress_report", "0002_alter_progressreport_topic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="progressreport",
            name="topic",
        ),
    ]
