# Generated by Django 3.2.4 on 2021-07-20 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("progress_report", "0003_remove_progressreport_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="progressreport",
            name="creator",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="users.user"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="creator",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="users.user"),
            preserve_default=False,
        ),
    ]
