# Generated by Django 3.2.4 on 2021-07-01 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comments", "0001_initial"),
        ("topics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicdiscussion",
            name="topic",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="topics.topic"),
        ),
    ]
