# Generated by Django 3.2.4 on 2021-07-01 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comments", "0002_topicdiscussion_topic"),
        ("topics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicdiscussion",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="startingcomment",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="comments.startingcomment",
            ),
        ),
        migrations.AddField(
            model_name="startingcomment",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="issuecomment",
            name="issue",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="topics.issue"),
        ),
        migrations.AddField(
            model_name="issuecomment",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="comments.issuecomment",
            ),
        ),
        migrations.AddField(
            model_name="issuecomment",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
