# Generated by Django 3.2.4 on 2021-07-01 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuecomment",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="comments.issuecomment",
            ),
        ),
        migrations.AlterField(
            model_name="startingcomment",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="comments.startingcomment",
            ),
        ),
        migrations.AlterField(
            model_name="topicdiscussion",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="comments.topicdiscussion",
            ),
        ),
    ]
