# Generated by Django 3.2.4 on 2021-07-15 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comments", "0004_auto_20210701_2049"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issuecomment",
            name="likes",
        ),
        migrations.RemoveField(
            model_name="startingcomment",
            name="likes",
        ),
        migrations.RemoveField(
            model_name="topicdiscussion",
            name="likes",
        ),
        migrations.CreateModel(
            name="TopicCommentLike",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("no_of_likes", models.PositiveIntegerField(default=0)),
                (
                    "comment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="likes", to="comments.topicdiscussion"
                    ),
                ),
                ("user", models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StartingCommentLike",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("no_of_likes", models.PositiveIntegerField(default=0)),
                (
                    "comment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="likes", to="comments.startingcomment"
                    ),
                ),
                ("user", models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IssueCommentLike",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("no_of_likes", models.PositiveIntegerField(default=0)),
                (
                    "comment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="likes", to="comments.issuecomment"
                    ),
                ),
                ("user", models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
