# Generated by Django 3.2.4 on 2021-07-19 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0006_auto_20210715_2214"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issuecomment",
            old_name="user",
            new_name="creator",
        ),
        migrations.RenameField(
            model_name="startingcomment",
            old_name="user",
            new_name="creator",
        ),
        migrations.RenameField(
            model_name="topicdiscussion",
            old_name="user",
            new_name="creator",
        ),
    ]
