# Generated by Django 3.2.4 on 2021-07-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=50)),
                ("content", models.TextField()),
                (
                    "_type",
                    models.CharField(
                        choices=[
                            ("su", "Success_stories"),
                            ("i", "Innovation"),
                            ("o", "Others"),
                            ("a", "Achievment"),
                            ("so", "Solution"),
                            ("p", "Problem"),
                        ],
                        max_length=30,
                    ),
                ),
                ("likes", models.PositiveIntegerField(default=0)),
                ("no_of_comments", models.PositiveIntegerField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("tags", models.ManyToManyField(blank=True, to="tags.Tag")),
            ],
        ),
    ]
