# Generated by Django 3.2.4 on 2021-07-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_blog_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="no_of_comments",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
