# Generated by Django 3.2.4 on 2021-07-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0005_auto_20210715_1731"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="views",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
