# Generated by Django 3.2.4 on 2021-07-19 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0006_blog_views"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="user",
            new_name="creator",
        ),
    ]
