# Generated by Django 3.2.4 on 2021-07-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0007_rename_user_blog_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="updated_on",
            field=models.DateTimeField(),
        ),
    ]
