# Generated by Django 3.2.4 on 2023-02-05 10:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_blog_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='front_img',
            field=cloudinary.models.CloudinaryField(default='localhost:80/media/i.png', max_length=255),
            preserve_default=False,
        ),
    ]
