# Generated by Django 3.2.4 on 2021-07-22 05:04

from django.db import migrations, models
import the_water_project.blogs.models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0008_alter_blog_updated_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="front_img",
            field=models.ImageField(blank=True, null=True, upload_to=the_water_project.blogs.models.unique_file_path),
        ),
    ]
